POST http://localhost:8080/events
content-Type: application/json
Authorization: 
{
    "title": "test_title",
    "description": "test_discription",
    "location": "test_location",
    "DateTime": "2029-10-25T15:30:00Z" //random dateTime
}