POST http://localhost:8080/events
content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlbnVtYmVyMkBnbWFpbC5jb20iLCJleGUiOjE3NzQ3MTAxOTIsInVzZXJJRCI6Mn0.PmQkjAxq46qRUidiJ2FEPPmPKuck8LNest5IwOvWWx0

{
    "title": "sla testando",
    "description": "amor",
    "location": "casa do pedrao",
    "DateTime": "2029-10-25T15:30:00Z"
}