DELETE http://localhost:8080/events/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhlIjoxNzc0NzI2NTIxLCJ1c2VySUQiOjF9.mGm9YVRi1NkonsYJoBe5Gk_zAkE9nioDiA6vYX6a0jI