PUT http://localhost:8080/events/3
Content-Type: application/json
Authorization: 

{
    "title": "test",
    "description": "test_discription",
    "location": "test_location",
    "DateTime": "2026-09-25T15:30:00Z" //random dateTime
}